import React from 'react';
import {Img,staticFile} from 'remotion';
import {C,pop,tween} from './design';
import {Check,SailMark,Star} from './Primitives';

const tile=(frame:number,start:number,x:number,y:number,w:number,h:number,color:string,rotation=0):React.CSSProperties=>{
 const p=pop(frame,start);return {position:'absolute',left:x,top:y,width:w,height:h,borderRadius:32,overflow:'hidden',background:color,color:C.ink,transform:`translate(${(540-x-w/2)*(1-p)}px,${(950-y-h/2)*(1-p)}px) scale(${.25+.75*p}) rotate(${rotation*p}deg)`,opacity:tween(frame/60,start,start+.25),transformOrigin:'50% 50%'};
};
export const Finale=({frame,t}:{frame:number;t:number})=>{
 const brand=pop(frame,66.05);const ring=tween(t,66.2,67.3);
 return <div data-finale style={{position:'absolute',inset:0,zIndex:6,opacity:tween(t,64.4,65.1)}}>
  <div style={{position:'absolute',left:70,top:122,fontSize:132,lineHeight:.94,fontWeight:700,letterSpacing:-8,color:C.paper}}>{['MAKE THE','MOMENT','YOURS.'].map((word,i)=><div key={word} style={{overflow:'hidden',paddingBottom:12}}><div style={{transform:`translateY(${(1-pop(frame,64.5,i*.1))*120}%)`,color:i===2?C.lime:C.paper}}>{word}</div></div>)}</div>
  <div style={tile(frame,64.65,80,650,530,430,C.paper,-3)}><Img src={staticFile('assets/hotel-room.jpg')} style={{width:'100%',height:235,objectFit:'cover'}}/><div style={{padding:'23px 26px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:33,fontWeight:700}}>A stay to look forward to.<Check color="#326b55"/></div><div style={{fontSize:26,color:'#657164',marginTop:12}}>The Meridian · Barcelona</div></div><span style={{position:'absolute',right:20,top:20}}><Star color={C.lime} size={43}/></span></div>
  <div style={tile(frame,64.8,655,680,335,445,'#dcd5ff',4)}><Img src={staticFile('assets/watch.jpg')} style={{width:'100%',height:265,objectFit:'cover'}}/><div style={{padding:25,fontSize:32,fontWeight:700,lineHeight:1.08}}>A great find.<br/>All yours.</div><span style={{position:'absolute',right:23,bottom:24}}><Check size={30}/></span></div>
  <div style={tile(frame,64.95,80,1170,480,310,C.mint,-2)}><div style={{padding:30}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:29,fontWeight:700}}>Northstar Air<Check/></div><div style={{display:'flex',gap:13,marginTop:25}}>{['11A','12A','13A'].map((s,i)=><div key={s} style={{width:112,height:80,display:'flex',alignItems:'center',justifyContent:'center',borderRadius:16,background:i===1?C.ink:'#ffffff88',color:i===1?C.paper:C.ink,fontSize:36,fontWeight:i===1?700:400,transform:i===1?'rotate(-4deg)':'none'}}>{s}</div>)}</div><div style={{fontSize:32,fontWeight:700,marginTop:22}}>A window. Just for you.</div></div></div>
  <div style={tile(frame,65.1,625,1210,370,310,'#ffdbca',3)}><div style={{padding:30}}><svg width="62" height="78" viewBox="0 0 62 78" fill="none"><path d="M12 4h25l15 15v54H12Z" fill={C.paper} stroke={C.ink} strokeWidth="3"/><path d="M23 31h18M23 43h18M23 55h11" stroke={C.ink} strokeWidth="3"/></svg><div style={{fontSize:33,fontWeight:700,lineHeight:1.1,marginTop:18}}>One less thing.</div><div style={{position:'absolute',right:25,top:28}}><Check/></div><div style={{fontSize:26,marginTop:12}}>Document received.</div></div></div>
  <svg width="1080" height="1920" style={{position:'absolute',inset:0,pointerEvents:'none'}}>{Array.from({length:12},(_,i)=>{const a=i*Math.PI/6;const r=160+ring*60;return <line key={i} x1={540+Math.cos(a)*r} y1={1692+Math.sin(a)*r*.55} x2={540+Math.cos(a)*(r+28)} y2={1692+Math.sin(a)*(r+28)*.55} stroke={i%2?C.purple:C.lime} strokeWidth="4" opacity={t<68?Math.sin(ring*Math.PI)*.65:0}/>})}</svg>
  <div style={{position:'absolute',left:72,right:72,top:1580,height:190,display:'flex',alignItems:'center',justifyContent:'center',gap:25,color:C.lime,background:C.ink,transform:`scale(${.8+.2*brand})`,opacity:tween(t,66.05,66.4)}}><SailMark size={123}/><span style={{fontSize:148,lineHeight:1,fontWeight:700,letterSpacing:-8}}>Sail</span><div style={{marginLeft:30,width:90,height:90,borderRadius:'50%',background:C.lime,display:'flex',alignItems:'center',justifyContent:'center'}}><Check size={55}/></div></div>
 </div>;
};
