import React from 'react';
import {Img,staticFile} from 'remotion';
import {C,linear,pop,tween} from './design';

export const SailMark=({size=52,color='currentColor'}:{size?:number;color?:string})=><svg width={size} height={size} viewBox="0 0 64 64" fill="none"><path d="M34 5 11 39l21-9L34 5Z" fill={color}/><path d="M37 20 56 52H9l22-18 6-14Z" fill={color}/><path d="M9 57h47" stroke={color} strokeWidth="3" strokeLinecap="round"/></svg>;
export const Check=({size=32,color=C.ink}:{size?:number;color?:string})=><svg width={size} height={size} viewBox="0 0 32 32"><path d="m7 16 6 6 13-14" stroke={color} strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/></svg>;
export const Arrow=({size=32,color='currentColor'}:{size?:number;color?:string})=><svg width={size} height={size} viewBox="0 0 32 32" fill="none"><path d="M5 16h22m-9-9 9 9-9 9" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
export const Star=({size=34,color=C.purple}:{size?:number;color?:string})=><svg width={size} height={size} viewBox="0 0 40 40"><path d="m20 2 5.5 12.5L38 20l-12.5 5.5L20 38l-5.5-12.5L2 20l12.5-5.5Z" fill={color}/></svg>;
export const Pill=({children,color=C.lime}:{children:React.ReactNode;color?:string})=><span style={{display:'inline-flex',alignItems:'center',gap:8,padding:'10px 17px',borderRadius:100,background:color,color:C.ink,fontSize:24,fontWeight:700}}>{children}</span>;

export const Title=({frame,start,lines,color=C.paper,size=92}:{frame:number;start:number;lines:string[];color?:string;size?:number})=><div style={{position:'absolute',left:72,top:112,right:62,zIndex:5,fontSize:size,fontWeight:700,lineHeight:1.02,letterSpacing:-5}}>{lines.map((text,i)=>{const p=pop(frame,start,i*.085);return <div key={text} style={{overflow:'hidden',paddingBottom:10}}><div style={{transform:`translateY(${(1-p)*110}%)`,color:i===lines.length-1?color:C.paper}}>{text}</div></div>})}</div>;

export const Phone=({children,prompt,frame,top,height,scale,opacity=1}:{children:React.ReactNode;prompt:string;frame:number;top:number;height:number;scale:number;opacity?:number})=><div data-design-phone style={{position:'absolute',left:170,top,width:740,height,transform:`scale(${scale})`,transformOrigin:'50% 0',opacity,zIndex:3,borderRadius:72,padding:10,background:'linear-gradient(125deg,#6a738f,#d4d8e4 45%,#505a75 90%)',border:'2px solid #a8aec4',boxShadow:'0 18px 0 #090b11'}}>
 <div style={{height:'100%',background:C.panel,border:'6px solid #080a11',borderRadius:62,overflow:'hidden',padding:'24px 30px 28px',display:'flex',flexDirection:'column',gap:18}}>
  <div style={{position:'relative',height:34,flexShrink:0,display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:22,fontWeight:700,color:C.paper,padding:'0 10px'}}><span>9:41</span><span style={{position:'absolute',left:'50%',transform:'translateX(-50%)',width:145,height:30,background:'#080a11',borderRadius:24}}/><span style={{fontSize:18}}>▮▮▮ ▱</span></div>
  <div style={{height:65,display:'flex',alignItems:'center',justifyContent:'space-between',flexShrink:0,borderBottom:`1px solid ${C.line}`,color:C.paper,fontSize:28,fontWeight:700}}><span>☰</span><span>Assistant</span><span style={{fontSize:38,fontWeight:400}}>＋</span></div>
  <div style={{alignSelf:'flex-end',padding:'19px 25px',borderRadius:'24px 24px 5px 24px',maxWidth:'92%',background:'#353050',color:'#eee6ff',fontSize:30,lineHeight:1.3,flexShrink:0}}>{prompt}</div>
  <div style={{display:'flex',alignItems:'center',gap:12,color:C.muted,fontSize:24,flexShrink:0}}><Star size={29}/><span>Assistant</span></div>
  <div style={{flex:1,minHeight:0,position:'relative'}}>{children}</div>
  <div style={{height:60,border:`1px solid ${C.line}`,borderRadius:22,padding:'0 21px',display:'flex',alignItems:'center',justifyContent:'space-between',color:C.muted,fontSize:23,flexShrink:0}}><span>＋</span><span>Message</span><Arrow size={24}/></div>
  <div style={{position:'absolute',bottom:20,left:'50%',transform:'translateX(-50%)',width:160,height:6,borderRadius:10,background:'#adb5cb'}}/>
 </div>
</div>;

export const Tap=({t,start,x,y,size=88}:{t:number;start:number;x:number;y:number;size?:number})=>{const p=linear(t,start,start+.55);if(t<start||p>=1)return null;return <div style={{position:'absolute',left:x-size/2,top:y-size/2,width:size,height:size,border:`3px solid ${C.lime}`,borderRadius:'50%',opacity:1-p,transform:`scale(${.45+p*1.1})`,pointerEvents:'none',zIndex:8}}/>};

export const Discovery=({t}:{t:number})=>{const p=tween(t,3.8,4.65);return <div style={{padding:'20px 10px',color:C.paper,fontSize:32,lineHeight:1.55}}><div style={{opacity:p}}>For a quieter stay, I’d suggest<br/><span style={{position:'relative',fontWeight:700,color:C.lime}}>The Meridian Hotel.<span style={{position:'absolute',height:4,left:0,bottom:-6,width:`${tween(t,5.9,6.7)*100}%`,background:C.lime,transform:'rotate(-1deg)'}}/></span></div><div style={{fontSize:28,marginTop:30,opacity:tween(t,4.3,5.1)}}>Bright rooms. Breakfast included.<br/>Easy access to the city.</div><div style={{color:C.purple,fontSize:25,marginTop:25,opacity:tween(t,4.7,5.5)}}><span style={{display:'flex',alignItems:'center',gap:10}}><Arrow size={25} color={C.purple}/>The Meridian Hotel · Website</span></div><div style={{position:'absolute',left:30,right:30,bottom:62,height:190,border:`2px dashed ${C.line}`,borderRadius:30,display:'flex',alignItems:'center',justifyContent:'center',opacity:tween(t,6.1,7.3),color:C.muted,fontSize:29}}>A mention. A link.</div></div>};

export const HotelWidget=({t,mini=false}:{t:number;mini?:boolean})=>{const confirmed=t>=20;const p=tween(t,8.2,9.7);return <div data-widget="hotel" style={{background:C.paper,borderRadius:30,overflow:'hidden',color:C.ink,clipPath:mini?'none':`inset(${(1-p)*100}% 0 0 0 round 30px)`,transform:mini?'none':`perspective(1400px) rotateX(${(1-p)*14}deg)`,transformOrigin:'50% 100%'}}>
 <div style={{padding:'23px 28px',display:'flex',alignItems:'center',justifyContent:'space-between',background:'#244b47',color:C.paper}}><div style={{fontSize:32,fontWeight:700,letterSpacing:-1}}>The Meridian</div><div style={{fontSize:18,letterSpacing:3}}>BARCELONA</div></div>
 <div style={{height:mini?150:250,position:'relative',overflow:'hidden'}}><Img src={staticFile('assets/hotel-room.jpg')} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1.12-.12*tween(t,11.6,15)})`}}/><div style={{position:'absolute',left:24,bottom:18}}><Pill color={C.paper}>A quieter kind of stay.</Pill></div></div>
 <div style={{padding:mini?18:28}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline'}}><div style={{fontSize:mini?28:36,fontWeight:700}}>Deluxe room</div><div style={{fontSize:mini?32:42,fontWeight:700}}>€220<span style={{fontSize:20,fontWeight:400}}> / night</span></div></div>
 {!mini&&<><div style={{display:'flex',gap:14,marginTop:24}}>{['17 OCT','19 OCT'].map((d,i)=><div key={d} style={{flex:1,padding:'16px 20px',border:`2px solid ${t>=16?C.blue:'#c9cebd'}`,borderRadius:16,background:'#fff'}}><div style={{fontSize:19,color:'#57675b',marginBottom:5}}>{i===0?'ARRIVAL':'DEPARTURE'}</div><div style={{fontSize:30}}>{d}</div></div>)}</div><div style={{marginTop:24,height:72,background:confirmed?'#244b47':C.ink,color:C.paper,borderRadius:16,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 23px',fontSize:28,fontWeight:700}}><span>{confirmed?'You’re going to Barcelona.':'Book this room'}</span>{confirmed?<Check color={C.mint}/>:<Arrow color={C.lime}/>}</div></>}
 </div>
 {!mini&&<Tap t={t} start={18.75} x={326} y={610}/>}
 </div>};

export const Catalogue=({t}:{t:number})=><div data-widget="order" style={{background:'#dcd5ff',borderRadius:30,overflow:'hidden',color:C.ink}}><div style={{padding:'24px 28px',fontSize:32,fontWeight:700,display:'flex',justifyContent:'space-between'}}><span>Atelier Goods</span><Star color={C.ink}/></div><Img src={staticFile('assets/watch.jpg')} style={{width:'100%',height:320,objectFit:'cover'}}/><div style={{padding:28}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:38,fontWeight:700}}><span>Everyday watch</span><span>€89</span></div><div style={{display:'flex',alignItems:'center',gap:14,fontSize:25,marginTop:20}}><span style={{width:28,height:28,borderRadius:'50%',background:'#323746',outline:'2px solid #323746',outlineOffset:4}}/>Graphite · In stock</div><div style={{height:72,marginTop:28,background:C.ink,color:C.paper,borderRadius:16,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 23px',fontSize:28,fontWeight:700}}><span>{t>24.65?'Order placed':'Place order'}</span>{t>24.65?<Check color={C.lime}/>:<Arrow color={C.lime}/>}</div></div></div>;

export const SeatWidget=({t,preview=false}:{t:number;preview?:boolean})=>{const ready=preview||t>=38.25;const selected=preview||t>=42.5;const sent=!preview&&t>=44.2;const done=preview||t>=53.25;const p=tween(t,38.1,38.65);return <div data-widget="seat" style={{background:C.paper,borderRadius:30,overflow:'hidden',color:C.ink}}>
 <div style={{background:'#284a70',padding:'24px 28px',display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{color:C.paper,fontSize:32,fontWeight:700,display:'flex',alignItems:'center',gap:10}}><Arrow size={30} color={C.paper}/> Northstar Air</div><span style={{color:'#bdcce0',fontSize:22}}>NS 218</span></div>
 <div style={{padding:28}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:30,fontWeight:700,marginBottom:24}}><span>{ready?'Choose your seat':'Checking live seats'}</span><span style={{fontSize:22,color:'#68727f'}}>BCN → LHR</span></div>
 <div style={{height:232,position:'relative'}}>{!ready?<div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center',gap:20}}>{[0,1,2].map(i=><div key={i} style={{width:25,height:25,borderRadius:'50%',background:C.blue,opacity:.25+.75*(Math.sin(t*5-i)+1)/2,transform:`translateY(${Math.sin(t*5-i)*9}px)`}}/>)}</div>:<div style={{display:'grid',gridTemplateColumns:'28px repeat(3,1fr) 22px repeat(3,1fr)',gap:10,opacity:preview?1:p}}>{[11,12,13].map((r)=>[<div key={`r${r}`} style={{display:'flex',alignItems:'center',fontSize:20,color:'#68727f'}}>{r}</div>,...Array.from({length:7},(_,c)=>{if(c===3)return <div key={`${r}-aisle`}/>;const letter='ABCDEF'[c>3?c-1:c];const target=r===12&&letter==='A';const unavailable=(r===11&&letter==='B')||(r===12&&letter==='E')||(r===13&&['C','F'].includes(letter));return <div key={`${r}${letter}`} style={{height:69,borderRadius:14,border:`2px solid ${target&&selected?(done?'#326b55':C.blue):'#bfc9d6'}`,background:target&&selected?(done?C.mint:C.blue):unavailable?'#d3d9e2':'#fff',color:target&&selected&&!done?C.paper:unavailable?'#7b8696':C.ink,display:'flex',alignItems:'center',justifyContent:'center',fontSize:26,fontWeight:target&&selected?700:400,transform:`scale(${target&&selected&&!done?1+.05*Math.sin(Math.min(t-42.5,.3)*Math.PI/.3):1})`}}>{target&&selected?'12A':letter}</div>})])}</div>}</div>
 <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:19,fontSize:26,fontWeight:700}}><span>{selected?'12A · Window':'Window seats available'}</span>{done&&<span style={{display:'flex',alignItems:'center',gap:6,color:'#326b55',fontSize:24}}><Check size={23} color="#326b55"/>Confirmed</span>}</div>
 <div style={{height:72,marginTop:24,background:done?'#284a70':C.blue,color:C.paper,borderRadius:16,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 23px',fontSize:28,fontWeight:700,opacity:ready?1:.3}}><span>{done?'Your window seat is yours.':sent?'Reserving 12A…':selected?'Confirm 12A':'Select a seat'}</span>{done?<Check color={C.mint}/>:<Arrow color={C.lime}/>}</div>
 </div>{!preview&&<><Tap t={t} start={42.5} x={106} y={284} size={80}/><Tap t={t} start={43.7} x={326} y={535}/></>}
 </div>};

export const Upload=({t}:{t:number})=>{const p=linear(t,27.05,27.8);return <div data-widget="upload" style={{background:'#ffdbca',borderRadius:30,padding:34,color:C.ink}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:31,fontWeight:700}}><span>Secure document upload</span><svg width="32" height="36" viewBox="0 0 32 36" fill="none"><rect x="5" y="14" width="22" height="18" rx="5" stroke={C.ink} strokeWidth="3"/><path d="M10 14V9a6 6 0 0 1 12 0v5" stroke={C.ink} strokeWidth="3"/></svg></div><div style={{height:220,marginTop:28,border:'2px dashed #bf8b73',borderRadius:24,display:'flex',alignItems:'center',justifyContent:'center',gap:24}}><div style={{width:92,height:120,borderRadius:12,background:C.paper,padding:20,transform:`rotate(${-8+8*p}deg)`}}><div style={{width:50,height:7,background:'#bf8b73',margin:'12px 0'}}/><div style={{width:38,height:7,background:'#bf8b73',margin:'12px 0'}}/><div style={{width:45,height:7,background:'#bf8b73',margin:'12px 0'}}/></div><div><div style={{fontSize:28,fontWeight:700}}>Prescription.pdf</div><div style={{fontSize:24,marginTop:8}}>PDF · 240 KB</div></div></div><div style={{height:10,borderRadius:9,background:'#e4bda8',marginTop:30,overflow:'hidden'}}><div style={{height:'100%',width:`${p*100}%`,background:C.ink}}/></div><div style={{height:72,marginTop:25,background:C.ink,color:C.paper,borderRadius:16,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 23px',fontSize:28,fontWeight:700}}><span>{p>=1?'Document received':'Uploading…'}</span>{p>=1?<Check color={C.mint}/>:<Arrow color={C.orange}/>}</div></div>};
